# Generated by Django 4.2.2 on 2023-06-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='pickup_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
