# Generated by Django 4.2.2 on 2023-06-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicledetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='to_time',
            field=models.DateTimeField(),
        ),
    ]
